language: python
sudo: false

git:
  depth: 1

env:
  matrix:
    - LUA="lua 5.1" RDB_VER="http://download.rethinkdb.com/apt/pool/precise/main/r/rethinkdb/rethinkdb_2.3.0~0precise_amd64.deb"
    - LUA="lua 5.2" RDB_VER="http://download.rethinkdb.com/apt/pool/precise/main/r/rethinkdb/rethinkdb_2.3.0~0precise_amd64.deb"
    - LUA="lua 5.3" RDB_VER="http://download.rethinkdb.com/apt/pool/precise/main/r/rethinkdb/rethinkdb_2.3.0~0precise_amd64.deb"
    - LUA="luajit 2.0" RDB_VER="http://download.rethinkdb.com/apt/pool/precise/main/r/rethinkdb/rethinkdb_2.3.0~0precise_amd64.deb"
    - LUA="luajit 2.1" RDB_VER="http://download.rethinkdb.com/apt/pool/precise/main/r/rethinkdb/rethinkdb_2.3.0~0precise_amd64.deb"

before_install:
  - wget $RDB_VER
  - ar x *.deb
  - tar xvzf data.tar.gz
  - pip install hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin
  - luarocks install busted

install:
  - luarocks make

before_script:
  - ./usr/bin/rethinkdb --daemon

script:
  - busted spec
