language: python
python:
  - '3.3'
  - 'pypy3'
before_install:
  - 'sudo apt-get install liblua5.1-dev'
# command to install dependencies
install:
  - 'python build.py'
# command to run tests
script:
  - 'python build.py test'
