language: python

env:
  global:
    - LUAROCKS_BASE=luarocks-2.2.0
  matrix:
    - LUA=lua5.1 LUA_DEV=liblua5.1-dev
    - LUA=lua5.2 LUA_DEV=liblua5.2-dev

python:
  - '3.3'

before_install:
  - 'source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list'
  - 'wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -'
  - 'sudo apt-get update'
  - 'sudo apt-get install $LUA $LUA_DEV rethinkdb'
  # Install a recent luarocks release
  - wget http://luarocks.org/releases/$LUAROCKS_BASE.tar.gz
  - tar zxvpf $LUAROCKS_BASE.tar.gz
  - cd $LUAROCKS_BASE
  - ./configure
  - make build
  - sudo make install
  - sudo make bootstrap
  - cd $TRAVIS_BUILD_DIR

# command to install dependencies
install:
  - 'sudo python3 build.py install'

# add the python rethinkdb driver so that it can be used in test setup
before_script:
  - 'pip install rethinkdb'

# command to run tests
script:
  - 'python build.py -f'
